# Generated by Django 4.1.5 on 2023-01-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
